export enum SAMPER_NAME{
    Euler_a = 'Euler a',
    Euler = 'Euler',
    LMS = 'LMS',
    Heun = 'Heun',
    DPM2 = 'DPM2',
    DPM2_a = 'Euler',
    DPMPlusPlus2S_a = 'DPM++ 2S a',
    DPMPlusPlus2M = 'DPM++ 2M',
    DPMPlusPlusSDE = 'DPM++ SDE',
    DPM_fast = 'DPM fast',
    DPM_adaptive = 'DPM adaptive',
    LMSKarras = 'LMS Karras',
    DPM2Karras = 'DPM2_Karras',
    DPM2_a_Karras = 'DPM2 a Karras',
    DPMPlusPlus2S_a_Karras = 'DPM++ 2S a Karras',
    DPMPlusPlus2M_Karras = 'DPM++ 2M Karras',
    DPMPlusPlusSDE_Karras = 'DPM++ SDE Karras',
    DDIM = 'DDIM',
    PLMS = 'PLMS',
    UniPC = 'UniPC',
}